title: XOOPS Cube Legacy
email: xoopserver@gmail.com
description: >-
  XOOPS Cube is a a free Open Source Web Application Platform released under BSD
  license and Base Legacy modules released under GPL license.
baseurl: ''
url: 'https://xoopscube.github.io/'
twitter_username: xoopscube
github_username: xoopscube
markdown: kramdown
theme: minima
plugins:
  - jekyll-admin
  - jekyll-feed
  - jekyll-gist
  - jekyll-assets
